name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install OpenJDK 8
      run: |
        sudo apt update
        sudo apt install -y openjdk-8-jdk
        
    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
        
    - name: Build
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
