name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Install Gradle 6.9.4
      run: |
        wget https://services.gradle.org/distributions/gradle-6.9.4-bin.zip
        sudo unzip -d /opt/gradle gradle-6.9.4-bin.zip
        echo "GRADLE_HOME=/opt/gradle/gradle-6.9.4" >> $GITHUB_ENV
        echo "/opt/gradle/gradle-6.9.4/bin" >> $GITHUB_PATH
        
    - name: Build
      run: gradle assembleDebug --no-daemon
