name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Install compatible Gradle
      run: |
        sudo apt update
        sudo apt install -y gradle-6.9
        sudo update-alternatives --set gradle /usr/bin/gradle-6.9
        
    - name: Build
      run: gradle assembleDebug --no-daemon
